### ISSUE TITLE
Unable to access reports data without a sensor.

### ISSUE THREAD

**Issue by gaguevaras** [kike-canaries/android-hpma115s0#12]
A contributor who wishes to contribute to the codebase is unable to do so unless they have a sensor available. This is due to the unavailable `google-services.json` file which allows access to the firebase instance where these reports are being stored.

Debugging the application using an empty dataset is not feasible:

![screen](https://user-images.githubusercontent.com/726062/46708449-4850f200-cc04-11e8-9f4c-29c1e0df02b9.png)

![screen1](https://user-images.githubusercontent.com/726062/46708452-4b4be280-cc04-11e8-9cfb-f7242428ba03.png)

![screen2](https://user-images.githubusercontent.com/726062/46708460-50109680-cc04-11e8-9187-84ead874cf07.png)

![screen3](https://user-images.githubusercontent.com/726062/46708463-530b8700-cc04-11e8-955b-51d268c83339.png)

These are some possible solutions I'm proposing:

**Solution 1:** Allow contributors to have read-only access to the existing dataset.

**Solution 2:** Allow contributors to have access to a staging firebase instance which contains an appropriate dataset for testing.

**Solution 3:** Export the existing dataset to a JSON file which can later be imported by individual contributors to their own firebase instance.

**Comment by hpsaturn** [comment]
the issues is relationed or is similar with the next thread:
[Firebase UI Android issue 204](https://github.com/firebase/FirebaseUI-Android/issues/204)

The firebase dataset was ready for read only mode. **For loading data**, please for now start the app the first time, and then pass por onStop and onStart for load list data (**normal exit and start app**). 

I'm working on that. Thanks

**Comment by hpsaturn** [comment]
- [x] fixed refresh data issue on posts fragment (workaround for Firebase Recycler View)
- [x] added refresh method for update data on scroll fragments
- [x] updated string message on empty recycler view
