### ISSUE TITLE
App crashes upon selecting "Unpair..." from the popup menu

### ISSUE THREAD

**Issue by gaguevaras** [kike-canaries/android-hpma115s0#13]
## Expected Behavior

App does not crash

## Current Behavior

App crashes with `IllegalStateException`.

## Steps to Reproduce

1.  Select popup menu without any paired devices.
2. Select "Unpair..."
3. App Crashes.

**Comment by hpsaturn** [comment]
This issue is alive in bluetooth disabled situation. If the user go to disabling bluetooth and then execute the unpairing action, the app go to crash

**Comment by hpsaturn** [comment]
issue fixed in last release.
