### ISSUE TITLE
Bug: The views merge when change from one activity to another fast.

### ISSUE THREAD

**Issue by juanpa097** [kike-canaries/android-hpma115s0#50]
## Steps to Reproduce

1. Open the app
2. Swipe fast from Map to Settings

## Screen Recording

![ezgif-5-f9d622bf3301](https://user-images.githubusercontent.com/15882623/83582899-72a5a080-a508-11ea-9189-5b9b2314f6fb.gif)

**Comment by hpsaturn** [comment]
Maybe it already fixed with last merge pull request #54 please if you can review it
